plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'eu.kanade.tachiyomi.extension.pt.flowermanga'
    compileSdk 34

    defaultConfig {
        applicationId 'eu.kanade.tachiyomi.extension.pt.flowermanga'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.github.keiyoushi:extensions-source:main'
}
