name: Compile Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Gradle Wrapper Basico
        run: |
          gradle wrapper --gradle-version 8.4
          chmod +x gradlew

      - name: Compilar APK da Extensao
        run: ./gradlew assembleDebug
